name: CI/CD Tienda Perritos - Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # Login en Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build y Push a Docker Hub
      - name: Build imagen Backend y push a Docker Hub
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USER }}/tienda-backend:latest .
          docker push ${{ secrets.DOCKER_USER }}/tienda-backend:latest

      # Configurar AWS para usar SSM
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Despliegue en EC2
      - name: Desplegar Backend vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Actualizar tienda-backend desde Docker Hub" \
            --parameters '{"commands":[
              "set -e",
              "sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}",
              "sudo docker pull ${{ secrets.DOCKER_USER }}/tienda-backend:latest",
              "sudo docker stop tienda-backend || true",
              "sudo docker rm tienda-backend || true",
              "sudo docker run -d --name tienda-backend -p 3001:3001 ${{ secrets.DOCKER_USER }}/tienda-backend:latest"
            ]}' \
            --output text